#!/usr/bin/env python3
# Copyright: (c)2012 Ardavon Falls
#
# This file is part of xsd-tools.
#
# Emit one gtest .cpp per round-trip target, with one TEST() per example XSD
# in the corpus. CMake runs this at configure time and compiles the output
# into the xsdb-test executable. Each test generates a binding + driver via
# libxsdb in-process (see roundtrip_util) and builds/runs the result; legs are
# GTEST_SKIP-gated on toolchain availability.

import os
import re
import sys

# (suite name, helper fn, list of required programs, output file)
TARGETS = [
    ("PythonSaxRoundtrip", "pythonRoundtrip", ["python3"],
     "roundtrip_python_sax.cpp"),
    ("CXmlExpatRoundtrip", "cExpatRoundtrip", ["cc"],
     "roundtrip_c_xml_expat.cpp"),
    ("CXmlExpatDomRoundtrip", "cExpatDomRoundtrip", ["cc"],
     "roundtrip_c_xml_expat_dom.cpp"),
    ("JavaJsonRoundtrip", "javaRoundtrip", ["mvn", "java"],
     "roundtrip_java_json.cpp"),
    ("JavaXmlRoundtrip", "javaXmlRoundtrip", ["mvn", "java"],
     "roundtrip_java_xml.cpp"),
]

# Targets emitted by default.
ENABLED = {"PythonSaxRoundtrip", "CXmlExpatRoundtrip", "CXmlExpatDomRoundtrip",
           "JavaJsonRoundtrip", "JavaXmlRoundtrip"}

# Round-trips known to fail for reasons unrelated to the build (e.g. defects
# in a template's test-value generation). Emitted with gtest's DISABLED_
# prefix so they are visible but do not fail the suite. Empty == none.
KNOWN_FAILING = {}

HEADER = """// AUTO-GENERATED by gen_roundtrip_tests.py -- do not edit.
#include "roundtrip_util.hpp"
#include <gtest/gtest.h>

"""

TEST_TMPL = """TEST({suite}, {name}) {{
{gates}  EXPECT_TRUE(xsdtest::{fn}("{xsd}"));
}}
"""


def sanitize(name):
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def gates_for(reqs):
    lines = []
    for prog in reqs:
        lines.append(
            '  if (!xsdtest::programAvailable("{p}")) '
            'GTEST_SKIP() << "{p} not available";\n'.format(p=prog))
    return "".join(lines)


def main(argv):
    if len(argv) != 3:
        sys.stderr.write(
            "usage: gen_roundtrip_tests.py <corpus_dir> <out_dir>\n")
        return 2
    corpus_dir, out_dir = argv[1], argv[2]
    xsds = sorted(
        os.path.join(corpus_dir, f)
        for f in os.listdir(corpus_dir) if f.endswith(".xsd"))
    os.makedirs(out_dir, exist_ok=True)

    for suite, fn, reqs, outfile in TARGETS:
        out_path = os.path.join(out_dir, outfile)
        if suite not in ENABLED:
            # Emit an empty TU so the CMake source list stays stable.
            with open(out_path, "w") as fh:
                fh.write(HEADER)
            continue
        gates = gates_for(reqs)
        known_failing = KNOWN_FAILING.get(suite, set())
        with open(out_path, "w") as fh:
            fh.write(HEADER)
            for xsd in xsds:
                base = os.path.splitext(os.path.basename(xsd))[0]
                name = sanitize(base)
                if base in known_failing:
                    name = "DISABLED_" + name
                fh.write(TEST_TMPL.format(
                    suite=suite, name=name, gates=gates, fn=fn,
                    xsd=os.path.abspath(xsd)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
