name: windows-arm64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-arm64:
    uses: ./.github/workflows/_build-windows.yml
    with:
      os: windows-11-arm
