#!/usr/bin/env python3
"""Quickstart endpoint 1 (Python / python-sax).

Produces the initial <message> and writes it to stdout. There is no input: this
is the head of the relay. Every class used here (xml_message, xml_header, …)
was generated by xsdb from message.xsd — this program only fills in values and
marshals.
"""
import io
import sys

import message  # generated by: xsdb python-sax message.xsd > message.py


def make_hop(name, lang, seq):
    endpoint = message.xml_endpoint()
    endpoint._content = [name]
    language = message.xml_lang()
    language._content = [lang]
    hop = message.xml_hop()
    hop._seq = seq
    hop._content = [endpoint, language]
    return hop


def main():
    root = message.xml_message_xsd()

    # header: a subject + a faceted priority (1..5), plus id/kind attributes
    subject = message.xml_subject()
    subject._content = ["build the bindings"]
    priority = message.xml_priority()
    priority._content = [3]
    header = message.xml_header()
    header._id = "msg-001"
    header._kind = "request"
    header._content = [subject, priority]

    msg = message.xml_message()
    msg._content = [header, make_hop("ep1", "python", 1)]
    root._content = [msg]

    out = io.StringIO()
    root.marshal(out)
    sys.stdout.write(out.getvalue())


if __name__ == "__main__":
    main()
