#!/usr/bin/env python3
"""Quickstart endpoint 4 (Python / python-sax).

Reads a <message> from stdin (produced upstream by the Java endpoint),
unmarshals it with the generated bindings, appends this endpoint's <hop>, and
writes the whole message back to stdout for the next endpoint. The header is
left untouched.
"""
import io
import sys

import message  # generated by: xsdb python-sax message.xsd > message.py


def main():
    root = message.xml_message_xsd()
    root.unmarshal(io.StringIO(sys.stdin.read()))
    msg = root._content[0]  # the <message> element

    hops = [c for c in msg._content if isinstance(c, message.xml_hop)]

    endpoint = message.xml_endpoint()
    endpoint._content = ["ep4"]
    language = message.xml_lang()
    language._content = ["python"]
    hop = message.xml_hop()
    hop._seq = len(hops) + 1
    hop._content = [endpoint, language]
    msg._content.append(hop)

    out = io.StringIO()
    root.marshal(out)
    sys.stdout.write(out.getvalue())


if __name__ == "__main__":
    main()
